/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite
import org.openapitools.client.models.CategoryStatisticCategoryStatisticitemread
import org.openapitools.client.models.CategoryStatisticCategoryStatisticreadCategoryStatisticitemread
import org.openapitools.client.models.CategoryStatisticCategoryStatisticwrite

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success

class CategoryStatisticApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Retrieves the collection of CategoryStatistic resources.
     * Retrieves the collection of CategoryStatistic resources.
     * @param page The collection page number (optional, default to 1)
     * @return kotlin.collections.List<CategoryStatisticCategoryStatisticitemread>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiCategoryStatisticsGetCollection(page: kotlin.Int? = 1) : kotlin.collections.List<CategoryStatisticCategoryStatisticitemread> {
        val localVarResponse = apiCategoryStatisticsGetCollectionWithHttpInfo(page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CategoryStatisticCategoryStatisticitemread>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieves the collection of CategoryStatistic resources.
     * Retrieves the collection of CategoryStatistic resources.
     * @param page The collection page number (optional, default to 1)
     * @return ApiResponse<kotlin.collections.List<CategoryStatisticCategoryStatisticitemread>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiCategoryStatisticsGetCollectionWithHttpInfo(page: kotlin.Int?) : ApiResponse<kotlin.collections.List<CategoryStatisticCategoryStatisticitemread>?> {
        val localVariableConfig = apiCategoryStatisticsGetCollectionRequestConfig(page = page)

        return request<Unit, kotlin.collections.List<CategoryStatisticCategoryStatisticitemread>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiCategoryStatisticsGetCollection
     *
     * @param page The collection page number (optional, default to 1)
     * @return RequestConfig
     */
    fun apiCategoryStatisticsGetCollectionRequestConfig(page: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/category_statistics",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Removes the CategoryStatistic resource.
     * Removes the CategoryStatistic resource.
     * @param id CategoryStatistic identifier
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiCategoryStatisticsIdDelete(id: kotlin.String) : Unit {
        val localVarResponse = apiCategoryStatisticsIdDeleteWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Removes the CategoryStatistic resource.
     * Removes the CategoryStatistic resource.
     * @param id CategoryStatistic identifier
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiCategoryStatisticsIdDeleteWithHttpInfo(id: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = apiCategoryStatisticsIdDeleteRequestConfig(id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiCategoryStatisticsIdDelete
     *
     * @param id CategoryStatistic identifier
     * @return RequestConfig
     */
    fun apiCategoryStatisticsIdDeleteRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/category_statistics/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Retrieves a CategoryStatistic resource.
     * Retrieves a CategoryStatistic resource.
     * @param id CategoryStatistic identifier
     * @return CategoryStatisticCategoryStatisticreadCategoryStatisticitemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiCategoryStatisticsIdGet(id: kotlin.String) : CategoryStatisticCategoryStatisticreadCategoryStatisticitemread {
        val localVarResponse = apiCategoryStatisticsIdGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CategoryStatisticCategoryStatisticreadCategoryStatisticitemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieves a CategoryStatistic resource.
     * Retrieves a CategoryStatistic resource.
     * @param id CategoryStatistic identifier
     * @return ApiResponse<CategoryStatisticCategoryStatisticreadCategoryStatisticitemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiCategoryStatisticsIdGetWithHttpInfo(id: kotlin.String) : ApiResponse<CategoryStatisticCategoryStatisticreadCategoryStatisticitemread?> {
        val localVariableConfig = apiCategoryStatisticsIdGetRequestConfig(id = id)

        return request<Unit, CategoryStatisticCategoryStatisticreadCategoryStatisticitemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiCategoryStatisticsIdGet
     *
     * @param id CategoryStatistic identifier
     * @return RequestConfig
     */
    fun apiCategoryStatisticsIdGetRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/category_statistics/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Updates the CategoryStatistic resource.
     * Updates the CategoryStatistic resource.
     * @param id CategoryStatistic identifier
     * @param categoryStatisticCategoryStatisticwrite The updated CategoryStatistic resource
     * @return CategoryStatisticCategoryStatisticreadCategoryStatisticitemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiCategoryStatisticsIdPatch(id: kotlin.String, categoryStatisticCategoryStatisticwrite: CategoryStatisticCategoryStatisticwrite) : CategoryStatisticCategoryStatisticreadCategoryStatisticitemread {
        val localVarResponse = apiCategoryStatisticsIdPatchWithHttpInfo(id = id, categoryStatisticCategoryStatisticwrite = categoryStatisticCategoryStatisticwrite)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CategoryStatisticCategoryStatisticreadCategoryStatisticitemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Updates the CategoryStatistic resource.
     * Updates the CategoryStatistic resource.
     * @param id CategoryStatistic identifier
     * @param categoryStatisticCategoryStatisticwrite The updated CategoryStatistic resource
     * @return ApiResponse<CategoryStatisticCategoryStatisticreadCategoryStatisticitemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiCategoryStatisticsIdPatchWithHttpInfo(id: kotlin.String, categoryStatisticCategoryStatisticwrite: CategoryStatisticCategoryStatisticwrite) : ApiResponse<CategoryStatisticCategoryStatisticreadCategoryStatisticitemread?> {
        val localVariableConfig = apiCategoryStatisticsIdPatchRequestConfig(id = id, categoryStatisticCategoryStatisticwrite = categoryStatisticCategoryStatisticwrite)

        return request<CategoryStatisticCategoryStatisticwrite, CategoryStatisticCategoryStatisticreadCategoryStatisticitemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiCategoryStatisticsIdPatch
     *
     * @param id CategoryStatistic identifier
     * @param categoryStatisticCategoryStatisticwrite The updated CategoryStatistic resource
     * @return RequestConfig
     */
    fun apiCategoryStatisticsIdPatchRequestConfig(id: kotlin.String, categoryStatisticCategoryStatisticwrite: CategoryStatisticCategoryStatisticwrite) : RequestConfig<CategoryStatisticCategoryStatisticwrite> {
        val localVariableBody = categoryStatisticCategoryStatisticwrite
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/merge-patch+json"
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/category_statistics/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Creates a CategoryStatistic resource.
     * Creates a CategoryStatistic resource.
     * @param categoryStatisticCategoryStatisticcreateCategoryStatisticwrite The new CategoryStatistic resource
     * @return CategoryStatisticCategoryStatisticreadCategoryStatisticitemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiCategoryStatisticsPost(categoryStatisticCategoryStatisticcreateCategoryStatisticwrite: CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite) : CategoryStatisticCategoryStatisticreadCategoryStatisticitemread {
        val localVarResponse = apiCategoryStatisticsPostWithHttpInfo(categoryStatisticCategoryStatisticcreateCategoryStatisticwrite = categoryStatisticCategoryStatisticcreateCategoryStatisticwrite)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CategoryStatisticCategoryStatisticreadCategoryStatisticitemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Creates a CategoryStatistic resource.
     * Creates a CategoryStatistic resource.
     * @param categoryStatisticCategoryStatisticcreateCategoryStatisticwrite The new CategoryStatistic resource
     * @return ApiResponse<CategoryStatisticCategoryStatisticreadCategoryStatisticitemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiCategoryStatisticsPostWithHttpInfo(categoryStatisticCategoryStatisticcreateCategoryStatisticwrite: CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite) : ApiResponse<CategoryStatisticCategoryStatisticreadCategoryStatisticitemread?> {
        val localVariableConfig = apiCategoryStatisticsPostRequestConfig(categoryStatisticCategoryStatisticcreateCategoryStatisticwrite = categoryStatisticCategoryStatisticcreateCategoryStatisticwrite)

        return request<CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite, CategoryStatisticCategoryStatisticreadCategoryStatisticitemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiCategoryStatisticsPost
     *
     * @param categoryStatisticCategoryStatisticcreateCategoryStatisticwrite The new CategoryStatistic resource
     * @return RequestConfig
     */
    fun apiCategoryStatisticsPostRequestConfig(categoryStatisticCategoryStatisticcreateCategoryStatisticwrite: CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite) : RequestConfig<CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite> {
        val localVariableBody = categoryStatisticCategoryStatisticcreateCategoryStatisticwrite
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/category_statistics",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
