/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.StatisticValueStatisticValuecreateStatisticValuewrite
import org.openapitools.client.models.StatisticValueStatisticValueitemread
import org.openapitools.client.models.StatisticValueStatisticValuereadStatisticValueitemread
import org.openapitools.client.models.StatisticValueStatisticValuewrite

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success

class StatisticValueApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Retrieves the collection of StatisticValue resources.
     * Retrieves the collection of StatisticValue resources.
     * @param page The collection page number (optional, default to 1)
     * @return kotlin.collections.List<StatisticValueStatisticValueitemread>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiStatisticValuesGetCollection(page: kotlin.Int? = 1) : kotlin.collections.List<StatisticValueStatisticValueitemread> {
        val localVarResponse = apiStatisticValuesGetCollectionWithHttpInfo(page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<StatisticValueStatisticValueitemread>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieves the collection of StatisticValue resources.
     * Retrieves the collection of StatisticValue resources.
     * @param page The collection page number (optional, default to 1)
     * @return ApiResponse<kotlin.collections.List<StatisticValueStatisticValueitemread>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiStatisticValuesGetCollectionWithHttpInfo(page: kotlin.Int?) : ApiResponse<kotlin.collections.List<StatisticValueStatisticValueitemread>?> {
        val localVariableConfig = apiStatisticValuesGetCollectionRequestConfig(page = page)

        return request<Unit, kotlin.collections.List<StatisticValueStatisticValueitemread>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiStatisticValuesGetCollection
     *
     * @param page The collection page number (optional, default to 1)
     * @return RequestConfig
     */
    fun apiStatisticValuesGetCollectionRequestConfig(page: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/statistic_values",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Removes the StatisticValue resource.
     * Removes the StatisticValue resource.
     * @param id StatisticValue identifier
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiStatisticValuesIdDelete(id: kotlin.String) : Unit {
        val localVarResponse = apiStatisticValuesIdDeleteWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Removes the StatisticValue resource.
     * Removes the StatisticValue resource.
     * @param id StatisticValue identifier
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiStatisticValuesIdDeleteWithHttpInfo(id: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = apiStatisticValuesIdDeleteRequestConfig(id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiStatisticValuesIdDelete
     *
     * @param id StatisticValue identifier
     * @return RequestConfig
     */
    fun apiStatisticValuesIdDeleteRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/statistic_values/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Retrieves a StatisticValue resource.
     * Retrieves a StatisticValue resource.
     * @param id StatisticValue identifier
     * @return StatisticValueStatisticValuereadStatisticValueitemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiStatisticValuesIdGet(id: kotlin.String) : StatisticValueStatisticValuereadStatisticValueitemread {
        val localVarResponse = apiStatisticValuesIdGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StatisticValueStatisticValuereadStatisticValueitemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieves a StatisticValue resource.
     * Retrieves a StatisticValue resource.
     * @param id StatisticValue identifier
     * @return ApiResponse<StatisticValueStatisticValuereadStatisticValueitemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiStatisticValuesIdGetWithHttpInfo(id: kotlin.String) : ApiResponse<StatisticValueStatisticValuereadStatisticValueitemread?> {
        val localVariableConfig = apiStatisticValuesIdGetRequestConfig(id = id)

        return request<Unit, StatisticValueStatisticValuereadStatisticValueitemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiStatisticValuesIdGet
     *
     * @param id StatisticValue identifier
     * @return RequestConfig
     */
    fun apiStatisticValuesIdGetRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/statistic_values/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Updates the StatisticValue resource.
     * Updates the StatisticValue resource.
     * @param id StatisticValue identifier
     * @param statisticValueStatisticValuewrite The updated StatisticValue resource
     * @return StatisticValueStatisticValuereadStatisticValueitemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiStatisticValuesIdPatch(id: kotlin.String, statisticValueStatisticValuewrite: StatisticValueStatisticValuewrite) : StatisticValueStatisticValuereadStatisticValueitemread {
        val localVarResponse = apiStatisticValuesIdPatchWithHttpInfo(id = id, statisticValueStatisticValuewrite = statisticValueStatisticValuewrite)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StatisticValueStatisticValuereadStatisticValueitemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Updates the StatisticValue resource.
     * Updates the StatisticValue resource.
     * @param id StatisticValue identifier
     * @param statisticValueStatisticValuewrite The updated StatisticValue resource
     * @return ApiResponse<StatisticValueStatisticValuereadStatisticValueitemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiStatisticValuesIdPatchWithHttpInfo(id: kotlin.String, statisticValueStatisticValuewrite: StatisticValueStatisticValuewrite) : ApiResponse<StatisticValueStatisticValuereadStatisticValueitemread?> {
        val localVariableConfig = apiStatisticValuesIdPatchRequestConfig(id = id, statisticValueStatisticValuewrite = statisticValueStatisticValuewrite)

        return request<StatisticValueStatisticValuewrite, StatisticValueStatisticValuereadStatisticValueitemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiStatisticValuesIdPatch
     *
     * @param id StatisticValue identifier
     * @param statisticValueStatisticValuewrite The updated StatisticValue resource
     * @return RequestConfig
     */
    fun apiStatisticValuesIdPatchRequestConfig(id: kotlin.String, statisticValueStatisticValuewrite: StatisticValueStatisticValuewrite) : RequestConfig<StatisticValueStatisticValuewrite> {
        val localVariableBody = statisticValueStatisticValuewrite
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/merge-patch+json"
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/statistic_values/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Creates a StatisticValue resource.
     * Creates a StatisticValue resource.
     * @param statisticValueStatisticValuecreateStatisticValuewrite The new StatisticValue resource
     * @return StatisticValueStatisticValuereadStatisticValueitemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiStatisticValuesPost(statisticValueStatisticValuecreateStatisticValuewrite: StatisticValueStatisticValuecreateStatisticValuewrite) : StatisticValueStatisticValuereadStatisticValueitemread {
        val localVarResponse = apiStatisticValuesPostWithHttpInfo(statisticValueStatisticValuecreateStatisticValuewrite = statisticValueStatisticValuecreateStatisticValuewrite)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StatisticValueStatisticValuereadStatisticValueitemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Creates a StatisticValue resource.
     * Creates a StatisticValue resource.
     * @param statisticValueStatisticValuecreateStatisticValuewrite The new StatisticValue resource
     * @return ApiResponse<StatisticValueStatisticValuereadStatisticValueitemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiStatisticValuesPostWithHttpInfo(statisticValueStatisticValuecreateStatisticValuewrite: StatisticValueStatisticValuecreateStatisticValuewrite) : ApiResponse<StatisticValueStatisticValuereadStatisticValueitemread?> {
        val localVariableConfig = apiStatisticValuesPostRequestConfig(statisticValueStatisticValuecreateStatisticValuewrite = statisticValueStatisticValuecreateStatisticValuewrite)

        return request<StatisticValueStatisticValuecreateStatisticValuewrite, StatisticValueStatisticValuereadStatisticValueitemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiStatisticValuesPost
     *
     * @param statisticValueStatisticValuecreateStatisticValuewrite The new StatisticValue resource
     * @return RequestConfig
     */
    fun apiStatisticValuesPostRequestConfig(statisticValueStatisticValuecreateStatisticValuewrite: StatisticValueStatisticValuecreateStatisticValuewrite) : RequestConfig<StatisticValueStatisticValuecreateStatisticValuewrite> {
        val localVariableBody = statisticValueStatisticValuecreateStatisticValuewrite
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/statistic_values",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
