/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param atId 
 * @param atType 
 * @param hydraColonFirst 
 * @param hydraColonLast 
 * @param hydraColonPrevious 
 * @param hydraColonNext 
 */


data class ApiCategoriesGetCollection200ResponseHydraView (

    @Json(name = "@id")
    val atId: kotlin.String? = null,

    @Json(name = "@type")
    val atType: kotlin.String? = null,

    @Json(name = "hydra:first")
    val hydraColonFirst: kotlin.String? = null,

    @Json(name = "hydra:last")
    val hydraColonLast: kotlin.String? = null,

    @Json(name = "hydra:previous")
    val hydraColonPrevious: kotlin.String? = null,

    @Json(name = "hydra:next")
    val hydraColonNext: kotlin.String? = null

) {


}

