/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ApiCategoriesGetCollection200ResponseHydraSearch
import org.openapitools.client.models.ApiCategoriesGetCollection200ResponseHydraView
import org.openapitools.client.models.ProductjsonldProductitemread

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param hydraColonMember 
 * @param hydraColonTotalItems 
 * @param hydraColonView 
 * @param hydraColonSearch 
 */


data class ApiProductsGetCollection200Response (

    @Json(name = "hydra:member")
    val hydraColonMember: kotlin.collections.List<ProductjsonldProductitemread>,

    @Json(name = "hydra:totalItems")
    val hydraColonTotalItems: kotlin.Int? = null,

    @Json(name = "hydra:view")
    val hydraColonView: ApiCategoriesGetCollection200ResponseHydraView? = null,

    @Json(name = "hydra:search")
    val hydraColonSearch: ApiCategoriesGetCollection200ResponseHydraSearch? = null

) {


}

