/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param atVocab 
 * @param hydra 
 */


data class CategoryJsonldCategoryReadCategoryItemReadContextOneOf (

    @Json(name = "@vocab")
    val atVocab: kotlin.String,

    @Json(name = "hydra")
    val hydra: CategoryJsonldCategoryReadCategoryItemReadContextOneOf.Hydra

) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     * 
     *
     * Values: httpColonSlashSlashWwwPeriodW3PeriodOrgSlashNsSlashHydraSlashCoreHash
     */
    @JsonClass(generateAdapter = false)
    enum class Hydra(val value: kotlin.String) {
        @Json(name = "http://www.w3.org/ns/hydra/core#") httpColonSlashSlashWwwPeriodW3PeriodOrgSlashNsSlashHydraSlashCoreHash("http://www.w3.org/ns/hydra/core#");
    }

}

