/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param id 
 * @param price 
 * @param boughAt 
 * @param validThrough 
 * @param isPaid 
 */


data class OrderItemOrderItemitemread (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "price")
    val price: kotlin.Int? = null,

    @Json(name = "boughAt")
    val boughAt: java.time.OffsetDateTime? = null,

    @Json(name = "validThrough")
    val validThrough: kotlin.Int? = null,

    @Json(name = "isPaid")
    val isPaid: kotlin.Boolean? = null

) {


}

