/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param statistic 
 * @param playerStatistics 
 * @param `value` 
 * @param level 
 */


data class StatisticValueStatisticValuereadStatisticValueitemread (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "statistic")
    val statistic: kotlin.String? = null,

    @Json(name = "playerStatistics")
    val playerStatistics: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    @Json(name = "level")
    val level: kotlin.Int? = null

) {


}

