/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.ApiTaskRewardsGetCollection200Response
import org.openapitools.client.models.TaskRewardTaskRewardcreateTaskRewardwrite
import org.openapitools.client.models.TaskRewardTaskRewarditemread
import org.openapitools.client.models.TaskRewardTaskRewardreadTaskRewarditemread
import org.openapitools.client.models.TaskRewardTaskRewardwrite
import org.openapitools.client.models.TaskRewardjsonldTaskRewardcreateTaskRewardwrite
import org.openapitools.client.models.TaskRewardjsonldTaskRewardreadTaskRewarditemread

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class TaskRewardApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Retrieves the collection of TaskReward resources.
     * Retrieves the collection of TaskReward resources.
     * @param page The collection page number (optional, default to 1)
     * @return kotlin.collections.List<TaskRewardTaskRewarditemread>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTaskRewardsGetCollection(page: kotlin.Int? = 1) : kotlin.collections.List<TaskRewardTaskRewarditemread> {
        val localVarResponse = apiTaskRewardsGetCollectionWithHttpInfo(page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<TaskRewardTaskRewarditemread>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieves the collection of TaskReward resources.
     * Retrieves the collection of TaskReward resources.
     * @param page The collection page number (optional, default to 1)
     * @return ApiResponse<kotlin.collections.List<TaskRewardTaskRewarditemread>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTaskRewardsGetCollectionWithHttpInfo(page: kotlin.Int?) : ApiResponse<kotlin.collections.List<TaskRewardTaskRewarditemread>?> {
        val localVariableConfig = apiTaskRewardsGetCollectionRequestConfig(page = page)

        return request<Unit, kotlin.collections.List<TaskRewardTaskRewarditemread>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiTaskRewardsGetCollection
     *
     * @param page The collection page number (optional, default to 1)
     * @return RequestConfig
     */
    fun apiTaskRewardsGetCollectionRequestConfig(page: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/task_rewards",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Removes the TaskReward resource.
     * Removes the TaskReward resource.
     * @param id TaskReward identifier
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTaskRewardsIdDelete(id: kotlin.String) : Unit {
        val localVarResponse = apiTaskRewardsIdDeleteWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Removes the TaskReward resource.
     * Removes the TaskReward resource.
     * @param id TaskReward identifier
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTaskRewardsIdDeleteWithHttpInfo(id: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = apiTaskRewardsIdDeleteRequestConfig(id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiTaskRewardsIdDelete
     *
     * @param id TaskReward identifier
     * @return RequestConfig
     */
    fun apiTaskRewardsIdDeleteRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/task_rewards/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Retrieves a TaskReward resource.
     * Retrieves a TaskReward resource.
     * @param id TaskReward identifier
     * @return TaskRewardTaskRewardreadTaskRewarditemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTaskRewardsIdGet(id: kotlin.String) : TaskRewardTaskRewardreadTaskRewarditemread {
        val localVarResponse = apiTaskRewardsIdGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TaskRewardTaskRewardreadTaskRewarditemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieves a TaskReward resource.
     * Retrieves a TaskReward resource.
     * @param id TaskReward identifier
     * @return ApiResponse<TaskRewardTaskRewardreadTaskRewarditemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTaskRewardsIdGetWithHttpInfo(id: kotlin.String) : ApiResponse<TaskRewardTaskRewardreadTaskRewarditemread?> {
        val localVariableConfig = apiTaskRewardsIdGetRequestConfig(id = id)

        return request<Unit, TaskRewardTaskRewardreadTaskRewarditemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiTaskRewardsIdGet
     *
     * @param id TaskReward identifier
     * @return RequestConfig
     */
    fun apiTaskRewardsIdGetRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/task_rewards/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Updates the TaskReward resource.
     * Updates the TaskReward resource.
     * @param id TaskReward identifier
     * @param taskRewardTaskRewardwrite The updated TaskReward resource
     * @return TaskRewardTaskRewardreadTaskRewarditemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTaskRewardsIdPatch(id: kotlin.String, taskRewardTaskRewardwrite: TaskRewardTaskRewardwrite) : TaskRewardTaskRewardreadTaskRewarditemread {
        val localVarResponse = apiTaskRewardsIdPatchWithHttpInfo(id = id, taskRewardTaskRewardwrite = taskRewardTaskRewardwrite)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TaskRewardTaskRewardreadTaskRewarditemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Updates the TaskReward resource.
     * Updates the TaskReward resource.
     * @param id TaskReward identifier
     * @param taskRewardTaskRewardwrite The updated TaskReward resource
     * @return ApiResponse<TaskRewardTaskRewardreadTaskRewarditemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTaskRewardsIdPatchWithHttpInfo(id: kotlin.String, taskRewardTaskRewardwrite: TaskRewardTaskRewardwrite) : ApiResponse<TaskRewardTaskRewardreadTaskRewarditemread?> {
        val localVariableConfig = apiTaskRewardsIdPatchRequestConfig(id = id, taskRewardTaskRewardwrite = taskRewardTaskRewardwrite)

        return request<TaskRewardTaskRewardwrite, TaskRewardTaskRewardreadTaskRewarditemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiTaskRewardsIdPatch
     *
     * @param id TaskReward identifier
     * @param taskRewardTaskRewardwrite The updated TaskReward resource
     * @return RequestConfig
     */
    fun apiTaskRewardsIdPatchRequestConfig(id: kotlin.String, taskRewardTaskRewardwrite: TaskRewardTaskRewardwrite) : RequestConfig<TaskRewardTaskRewardwrite> {
        val localVariableBody = taskRewardTaskRewardwrite
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/merge-patch+json"
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/task_rewards/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Creates a TaskReward resource.
     * Creates a TaskReward resource.
     * @param taskRewardTaskRewardcreateTaskRewardwrite The new TaskReward resource
     * @return TaskRewardTaskRewardreadTaskRewarditemread
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiTaskRewardsPost(taskRewardTaskRewardcreateTaskRewardwrite: TaskRewardTaskRewardcreateTaskRewardwrite) : TaskRewardTaskRewardreadTaskRewarditemread {
        val localVarResponse = apiTaskRewardsPostWithHttpInfo(taskRewardTaskRewardcreateTaskRewardwrite = taskRewardTaskRewardcreateTaskRewardwrite)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TaskRewardTaskRewardreadTaskRewarditemread
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Creates a TaskReward resource.
     * Creates a TaskReward resource.
     * @param taskRewardTaskRewardcreateTaskRewardwrite The new TaskReward resource
     * @return ApiResponse<TaskRewardTaskRewardreadTaskRewarditemread?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiTaskRewardsPostWithHttpInfo(taskRewardTaskRewardcreateTaskRewardwrite: TaskRewardTaskRewardcreateTaskRewardwrite) : ApiResponse<TaskRewardTaskRewardreadTaskRewarditemread?> {
        val localVariableConfig = apiTaskRewardsPostRequestConfig(taskRewardTaskRewardcreateTaskRewardwrite = taskRewardTaskRewardcreateTaskRewardwrite)

        return request<TaskRewardTaskRewardcreateTaskRewardwrite, TaskRewardTaskRewardreadTaskRewarditemread>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiTaskRewardsPost
     *
     * @param taskRewardTaskRewardcreateTaskRewardwrite The new TaskReward resource
     * @return RequestConfig
     */
    fun apiTaskRewardsPostRequestConfig(taskRewardTaskRewardcreateTaskRewardwrite: TaskRewardTaskRewardcreateTaskRewardwrite) : RequestConfig<TaskRewardTaskRewardcreateTaskRewardwrite> {
        val localVariableBody = taskRewardTaskRewardcreateTaskRewardwrite
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/ld+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/task_rewards",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
