/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param category 
 * @param multiplier 
 */


data class CategoryStatisticCategoryStatisticwrite (

    @Json(name = "category")
    val category: kotlin.String? = null,

    @Json(name = "multiplier")
    val multiplier: kotlin.Int? = null

) {


}

