/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param player 
 * @param atId 
 * @param atType 
 * @param id 
 * @param statisticValues 
 */


data class PlayerStatisticsjsonldPlayerStatisticsitemread (

    @Json(name = "player")
    val player: kotlin.String?,

    @Json(name = "@id")
    val atId: kotlin.String? = null,

    @Json(name = "@type")
    val atType: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "statisticValues")
    val statisticValues: kotlin.collections.List<kotlin.String>? = null

) {


}

