/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param user 
 * @param notificationSettings 
 * @param holidayMode 
 * @param languagePreferences 
 * @param darkMode 
 */


data class SettingsSettingsreadSettingsitemread (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "user")
    val user: kotlin.String? = null,

    @Json(name = "notificationSettings")
    val notificationSettings: kotlin.String? = null,

    @Json(name = "holidayMode")
    val holidayMode: kotlin.Boolean? = null,

    @Json(name = "languagePreferences")
    val languagePreferences: kotlin.String? = null,

    @Json(name = "darkMode")
    val darkMode: kotlin.Boolean? = null

) {


}

