/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CategoryJsonldCategoryReadCategoryItemReadContext

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param atContext 
 * @param atId 
 * @param atType 
 * @param id 
 * @param email 
 * @param enabled 
 * @param playerSettings 
 */


data class UserjsonldUserreadUseritemread (

    @Json(name = "@context")
    val atContext: CategoryJsonldCategoryReadCategoryItemReadContext? = null,

    @Json(name = "@id")
    val atId: kotlin.String? = null,

    @Json(name = "@type")
    val atType: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = true,

    @Json(name = "playerSettings")
    val playerSettings: kotlin.String? = null

) {


}

