/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ApiRewardItemsGetCollection200Response
import org.openapitools.client.models.ApiCategoriesGetCollection200ResponseHydraSearch
import org.openapitools.client.models.ApiCategoriesGetCollection200ResponseHydraView
import org.openapitools.client.models.RewardItemjsonldRewardItemitemread

class ApiRewardItemsGetCollection200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiRewardItemsGetCollection200Response
        //val modelInstance = ApiRewardItemsGetCollection200Response()

        // to test the property `hydraColonMember`
        should("test hydraColonMember") {
            // uncomment below to test the property
            //modelInstance.hydraColonMember shouldBe ("TODO")
        }

        // to test the property `hydraColonTotalItems`
        should("test hydraColonTotalItems") {
            // uncomment below to test the property
            //modelInstance.hydraColonTotalItems shouldBe ("TODO")
        }

        // to test the property `hydraColonView`
        should("test hydraColonView") {
            // uncomment below to test the property
            //modelInstance.hydraColonView shouldBe ("TODO")
        }

        // to test the property `hydraColonSearch`
        should("test hydraColonSearch") {
            // uncomment below to test the property
            //modelInstance.hydraColonSearch shouldBe ("TODO")
        }

    }
}
