/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CategoryJsonldCategoryReadCategoryItemReadContext
import org.openapitools.client.models.CategoryJsonldCategoryReadCategoryItemReadContextOneOf

class CategoryJsonldCategoryReadCategoryItemReadContextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryJsonldCategoryReadCategoryItemReadContext
        //val modelInstance = CategoryJsonldCategoryReadCategoryItemReadContext()

        // to test the property `atVocab`
        should("test atVocab") {
            // uncomment below to test the property
            //modelInstance.atVocab shouldBe ("TODO")
        }

        // to test the property `hydra`
        should("test hydra") {
            // uncomment below to test the property
            //modelInstance.hydra shouldBe ("TODO")
        }

    }
}
