/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CategoryStatisticjsonldCategoryStatisticcreateCategoryStatisticwrite

class CategoryStatisticjsonldCategoryStatisticcreateCategoryStatisticwriteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryStatisticjsonldCategoryStatisticcreateCategoryStatisticwrite
        //val modelInstance = CategoryStatisticjsonldCategoryStatisticcreateCategoryStatisticwrite()

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `statistic`
        should("test statistic") {
            // uncomment below to test the property
            //modelInstance.statistic shouldBe ("TODO")
        }

        // to test the property `multiplier`
        should("test multiplier") {
            // uncomment below to test the property
            //modelInstance.multiplier shouldBe ("TODO")
        }

    }
}
