/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CategoryStatisticjsonldCategoryStatisticitemread

class CategoryStatisticjsonldCategoryStatisticitemreadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryStatisticjsonldCategoryStatisticitemread
        //val modelInstance = CategoryStatisticjsonldCategoryStatisticitemread()

        // to test the property `atId`
        should("test atId") {
            // uncomment below to test the property
            //modelInstance.atId shouldBe ("TODO")
        }

        // to test the property `atType`
        should("test atType") {
            // uncomment below to test the property
            //modelInstance.atType shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `statistic`
        should("test statistic") {
            // uncomment below to test the property
            //modelInstance.statistic shouldBe ("TODO")
        }

        // to test the property `multiplier`
        should("test multiplier") {
            // uncomment below to test the property
            //modelInstance.multiplier shouldBe ("TODO")
        }

    }
}
