/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PlayerStatisticsjsonldPlayerStatisticsreadPlayerStatisticsitemread
import org.openapitools.client.models.CategoryJsonldCategoryReadCategoryItemReadContext

class PlayerStatisticsjsonldPlayerStatisticsreadPlayerStatisticsitemreadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerStatisticsjsonldPlayerStatisticsreadPlayerStatisticsitemread
        //val modelInstance = PlayerStatisticsjsonldPlayerStatisticsreadPlayerStatisticsitemread()

        // to test the property `player`
        should("test player") {
            // uncomment below to test the property
            //modelInstance.player shouldBe ("TODO")
        }

        // to test the property `atContext`
        should("test atContext") {
            // uncomment below to test the property
            //modelInstance.atContext shouldBe ("TODO")
        }

        // to test the property `atId`
        should("test atId") {
            // uncomment below to test the property
            //modelInstance.atId shouldBe ("TODO")
        }

        // to test the property `atType`
        should("test atType") {
            // uncomment below to test the property
            //modelInstance.atType shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `statisticValues`
        should("test statisticValues") {
            // uncomment below to test the property
            //modelInstance.statisticValues shouldBe ("TODO")
        }

    }
}
