/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PlayerStatisticsjsonldPlayerStatisticscreatePlayerStatisticswrite

class PlayerStatisticsjsonldPlayerStatisticscreatePlayerStatisticswriteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerStatisticsjsonldPlayerStatisticscreatePlayerStatisticswrite
        //val modelInstance = PlayerStatisticsjsonldPlayerStatisticscreatePlayerStatisticswrite()

        // to test the property `player`
        should("test player") {
            // uncomment below to test the property
            //modelInstance.player shouldBe ("TODO")
        }

        // to test the property `statisticValues`
        should("test statisticValues") {
            // uncomment below to test the property
            //modelInstance.statisticValues shouldBe ("TODO")
        }

    }
}
