/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PlayerPlayerwrite

class PlayerPlayerwriteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerPlayerwrite
        //val modelInstance = PlayerPlayerwrite()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `friends`
        should("test friends") {
            // uncomment below to test the property
            //modelInstance.friends shouldBe ("TODO")
        }

        // to test the property `obtainedRewards`
        should("test obtainedRewards") {
            // uncomment below to test the property
            //modelInstance.obtainedRewards shouldBe ("TODO")
        }

    }
}
