/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SettingsjsonldSettingsreadSettingsitemread
import org.openapitools.client.models.CategoryJsonldCategoryReadCategoryItemReadContext

class SettingsjsonldSettingsreadSettingsitemreadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsjsonldSettingsreadSettingsitemread
        //val modelInstance = SettingsjsonldSettingsreadSettingsitemread()

        // to test the property `atContext`
        should("test atContext") {
            // uncomment below to test the property
            //modelInstance.atContext shouldBe ("TODO")
        }

        // to test the property `atId`
        should("test atId") {
            // uncomment below to test the property
            //modelInstance.atId shouldBe ("TODO")
        }

        // to test the property `atType`
        should("test atType") {
            // uncomment below to test the property
            //modelInstance.atType shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `notificationSettings`
        should("test notificationSettings") {
            // uncomment below to test the property
            //modelInstance.notificationSettings shouldBe ("TODO")
        }

        // to test the property `holidayMode`
        should("test holidayMode") {
            // uncomment below to test the property
            //modelInstance.holidayMode shouldBe ("TODO")
        }

        // to test the property `languagePreferences`
        should("test languagePreferences") {
            // uncomment below to test the property
            //modelInstance.languagePreferences shouldBe ("TODO")
        }

        // to test the property `darkMode`
        should("test darkMode") {
            // uncomment below to test the property
            //modelInstance.darkMode shouldBe ("TODO")
        }

    }
}
