/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SettingsSettingswrite

class SettingsSettingswriteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsSettingswrite
        //val modelInstance = SettingsSettingswrite()

        // to test the property `notificationSettings`
        should("test notificationSettings") {
            // uncomment below to test the property
            //modelInstance.notificationSettings shouldBe ("TODO")
        }

        // to test the property `holidayMode`
        should("test holidayMode") {
            // uncomment below to test the property
            //modelInstance.holidayMode shouldBe ("TODO")
        }

        // to test the property `languagePreferences`
        should("test languagePreferences") {
            // uncomment below to test the property
            //modelInstance.languagePreferences shouldBe ("TODO")
        }

        // to test the property `darkMode`
        should("test darkMode") {
            // uncomment below to test the property
            //modelInstance.darkMode shouldBe ("TODO")
        }

    }
}
