/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TaskRewardTaskRewardwrite

class TaskRewardTaskRewardwriteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaskRewardTaskRewardwrite
        //val modelInstance = TaskRewardTaskRewardwrite()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `experiencePoints`
        should("test experiencePoints") {
            // uncomment below to test the property
            //modelInstance.experiencePoints shouldBe ("TODO")
        }

    }
}
