/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TaskjsonldTaskcreateTaskwrite

class TaskjsonldTaskcreateTaskwriteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaskjsonldTaskcreateTaskwrite
        //val modelInstance = TaskjsonldTaskcreateTaskwrite()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `player`
        should("test player") {
            // uncomment below to test the property
            //modelInstance.player shouldBe ("TODO")
        }

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `difficulty`
        should("test difficulty") {
            // uncomment below to test the property
            //modelInstance.difficulty shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `completedAt`
        should("test completedAt") {
            // uncomment below to test the property
            //modelInstance.completedAt shouldBe ("TODO")
        }

    }
}
