/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UserjsonldUsercreateUserwrite

class UserjsonldUsercreateUserwriteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserjsonldUsercreateUserwrite
        //val modelInstance = UserjsonldUsercreateUserwrite()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `salt`
        should("test salt") {
            // uncomment below to test the property
            //modelInstance.salt shouldBe ("TODO")
        }

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `playerSettings`
        should("test playerSettings") {
            // uncomment below to test the property
            //modelInstance.playerSettings shouldBe ("TODO")
        }

    }
}
