/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UserjsonldUserreadUseritemread
import org.openapitools.client.models.CategoryJsonldCategoryReadCategoryItemReadContext

class UserjsonldUserreadUseritemreadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserjsonldUserreadUseritemread
        //val modelInstance = UserjsonldUserreadUseritemread()

        // to test the property `atContext`
        should("test atContext") {
            // uncomment below to test the property
            //modelInstance.atContext shouldBe ("TODO")
        }

        // to test the property `atId`
        should("test atId") {
            // uncomment below to test the property
            //modelInstance.atId shouldBe ("TODO")
        }

        // to test the property `atType`
        should("test atType") {
            // uncomment below to test the property
            //modelInstance.atType shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `playerSettings`
        should("test playerSettings") {
            // uncomment below to test the property
            //modelInstance.playerSettings shouldBe ("TODO")
        }

    }
}
