/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.CategoryStatisticApi
import org.openapitools.client.models.ApiCategoryStatisticsGetCollection200Response
import org.openapitools.client.models.CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite
import org.openapitools.client.models.CategoryStatisticCategoryStatisticitemread
import org.openapitools.client.models.CategoryStatisticCategoryStatisticreadCategoryStatisticitemread
import org.openapitools.client.models.CategoryStatisticCategoryStatisticwrite
import org.openapitools.client.models.CategoryStatisticjsonldCategoryStatisticcreateCategoryStatisticwrite
import org.openapitools.client.models.CategoryStatisticjsonldCategoryStatisticreadCategoryStatisticitemread

class CategoryStatisticApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryStatisticApi
        //val apiInstance = CategoryStatisticApi()

        // to test apiCategoryStatisticsGetCollection
        should("test apiCategoryStatisticsGetCollection") {
            // uncomment below to test apiCategoryStatisticsGetCollection
            //val page : kotlin.Int = 56 // kotlin.Int | The collection page number
            //val result : kotlin.collections.List<CategoryStatisticCategoryStatisticitemread> = apiInstance.apiCategoryStatisticsGetCollection(page)
            //result shouldBe ("TODO")
        }

        // to test apiCategoryStatisticsIdDelete
        should("test apiCategoryStatisticsIdDelete") {
            // uncomment below to test apiCategoryStatisticsIdDelete
            //val id : kotlin.String = id_example // kotlin.String | CategoryStatistic identifier
            //apiInstance.apiCategoryStatisticsIdDelete(id)
        }

        // to test apiCategoryStatisticsIdGet
        should("test apiCategoryStatisticsIdGet") {
            // uncomment below to test apiCategoryStatisticsIdGet
            //val id : kotlin.String = id_example // kotlin.String | CategoryStatistic identifier
            //val result : CategoryStatisticCategoryStatisticreadCategoryStatisticitemread = apiInstance.apiCategoryStatisticsIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test apiCategoryStatisticsIdPatch
        should("test apiCategoryStatisticsIdPatch") {
            // uncomment below to test apiCategoryStatisticsIdPatch
            //val id : kotlin.String = id_example // kotlin.String | CategoryStatistic identifier
            //val categoryStatisticCategoryStatisticwrite : CategoryStatisticCategoryStatisticwrite =  // CategoryStatisticCategoryStatisticwrite | The updated CategoryStatistic resource
            //val result : CategoryStatisticCategoryStatisticreadCategoryStatisticitemread = apiInstance.apiCategoryStatisticsIdPatch(id, categoryStatisticCategoryStatisticwrite)
            //result shouldBe ("TODO")
        }

        // to test apiCategoryStatisticsPost
        should("test apiCategoryStatisticsPost") {
            // uncomment below to test apiCategoryStatisticsPost
            //val categoryStatisticCategoryStatisticcreateCategoryStatisticwrite : CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite =  // CategoryStatisticCategoryStatisticcreateCategoryStatisticwrite | The new CategoryStatistic resource
            //val result : CategoryStatisticCategoryStatisticreadCategoryStatisticitemread = apiInstance.apiCategoryStatisticsPost(categoryStatisticCategoryStatisticcreateCategoryStatisticwrite)
            //result shouldBe ("TODO")
        }

    }
}
