/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.CategoryApi
import org.openapitools.client.models.ApiCategoriesGetCollection200Response
import org.openapitools.client.models.CategoryCategorycreateCategorywrite
import org.openapitools.client.models.CategoryCategoryitemread
import org.openapitools.client.models.CategoryCategoryreadCategoryitemread
import org.openapitools.client.models.CategoryCategorywriteCategoryupdate
import org.openapitools.client.models.CategoryjsonldCategorycreateCategorywrite
import org.openapitools.client.models.CategoryjsonldCategoryreadCategoryitemread

class CategoryApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategoryApi
        //val apiInstance = CategoryApi()

        // to test apiCategoriesGetCollection
        should("test apiCategoriesGetCollection") {
            // uncomment below to test apiCategoriesGetCollection
            //val page : kotlin.Int = 56 // kotlin.Int | The collection page number
            //val result : kotlin.collections.List<CategoryCategoryitemread> = apiInstance.apiCategoriesGetCollection(page)
            //result shouldBe ("TODO")
        }

        // to test apiCategoriesIdDelete
        should("test apiCategoriesIdDelete") {
            // uncomment below to test apiCategoriesIdDelete
            //val id : kotlin.String = id_example // kotlin.String | Category identifier
            //apiInstance.apiCategoriesIdDelete(id)
        }

        // to test apiCategoriesIdGet
        should("test apiCategoriesIdGet") {
            // uncomment below to test apiCategoriesIdGet
            //val id : kotlin.String = id_example // kotlin.String | Category identifier
            //val result : CategoryCategoryreadCategoryitemread = apiInstance.apiCategoriesIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test apiCategoriesIdPatch
        should("test apiCategoriesIdPatch") {
            // uncomment below to test apiCategoriesIdPatch
            //val id : kotlin.String = id_example // kotlin.String | Category identifier
            //val categoryCategorywriteCategoryupdate : CategoryCategorywriteCategoryupdate =  // CategoryCategorywriteCategoryupdate | The updated Category resource
            //val result : CategoryCategoryreadCategoryitemread = apiInstance.apiCategoriesIdPatch(id, categoryCategorywriteCategoryupdate)
            //result shouldBe ("TODO")
        }

        // to test apiCategoriesPost
        should("test apiCategoriesPost") {
            // uncomment below to test apiCategoriesPost
            //val categoryCategorycreateCategorywrite : CategoryCategorycreateCategorywrite =  // CategoryCategorycreateCategorywrite | The new Category resource
            //val result : CategoryCategoryreadCategoryitemread = apiInstance.apiCategoriesPost(categoryCategorycreateCategorywrite)
            //result shouldBe ("TODO")
        }

    }
}
