/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.StatisticValueApi
import org.openapitools.client.models.ApiStatisticValuesGetCollection200Response
import org.openapitools.client.models.StatisticValueStatisticValuecreateStatisticValuewrite
import org.openapitools.client.models.StatisticValueStatisticValueitemread
import org.openapitools.client.models.StatisticValueStatisticValuereadStatisticValueitemread
import org.openapitools.client.models.StatisticValueStatisticValuewrite
import org.openapitools.client.models.StatisticValuejsonldStatisticValuecreateStatisticValuewrite
import org.openapitools.client.models.StatisticValuejsonldStatisticValuereadStatisticValueitemread

class StatisticValueApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatisticValueApi
        //val apiInstance = StatisticValueApi()

        // to test apiStatisticValuesGetCollection
        should("test apiStatisticValuesGetCollection") {
            // uncomment below to test apiStatisticValuesGetCollection
            //val page : kotlin.Int = 56 // kotlin.Int | The collection page number
            //val result : kotlin.collections.List<StatisticValueStatisticValueitemread> = apiInstance.apiStatisticValuesGetCollection(page)
            //result shouldBe ("TODO")
        }

        // to test apiStatisticValuesIdDelete
        should("test apiStatisticValuesIdDelete") {
            // uncomment below to test apiStatisticValuesIdDelete
            //val id : kotlin.String = id_example // kotlin.String | StatisticValue identifier
            //apiInstance.apiStatisticValuesIdDelete(id)
        }

        // to test apiStatisticValuesIdGet
        should("test apiStatisticValuesIdGet") {
            // uncomment below to test apiStatisticValuesIdGet
            //val id : kotlin.String = id_example // kotlin.String | StatisticValue identifier
            //val result : StatisticValueStatisticValuereadStatisticValueitemread = apiInstance.apiStatisticValuesIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test apiStatisticValuesIdPatch
        should("test apiStatisticValuesIdPatch") {
            // uncomment below to test apiStatisticValuesIdPatch
            //val id : kotlin.String = id_example // kotlin.String | StatisticValue identifier
            //val statisticValueStatisticValuewrite : StatisticValueStatisticValuewrite =  // StatisticValueStatisticValuewrite | The updated StatisticValue resource
            //val result : StatisticValueStatisticValuereadStatisticValueitemread = apiInstance.apiStatisticValuesIdPatch(id, statisticValueStatisticValuewrite)
            //result shouldBe ("TODO")
        }

        // to test apiStatisticValuesPost
        should("test apiStatisticValuesPost") {
            // uncomment below to test apiStatisticValuesPost
            //val statisticValueStatisticValuecreateStatisticValuewrite : StatisticValueStatisticValuecreateStatisticValuewrite =  // StatisticValueStatisticValuecreateStatisticValuewrite | The new StatisticValue resource
            //val result : StatisticValueStatisticValuereadStatisticValueitemread = apiInstance.apiStatisticValuesPost(statisticValueStatisticValuecreateStatisticValuewrite)
            //result shouldBe ("TODO")
        }

    }
}
